"""update_coupon_definition

Revision ID: 20240923013632
Revises: 20240920164525
Create Date: 2024-09-23 01:47:57.123954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20240923013632'
down_revision: Union[str, None] = '20240920164525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_group_coupons', sa.Column('coupon_definition_id', sa.Integer(), nullable=True))
    op.add_column('member_group_coupons', sa.Column('name', sa.String(length=256), nullable=True))
    op.add_column('member_group_coupons', sa.Column('date_start', sa.Date(), nullable=True))
    op.add_column('member_group_coupons', sa.Column('date_end', sa.Date(), nullable=True))
    op.add_column('member_group_coupons', sa.Column('all_machines', sa.Boolean(), nullable=True))
    op.add_column('member_group_coupons', sa.Column('applicable_machines', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('member_group_coupons', sa.Column('user_redemption_period_limit', sa.Integer(), nullable=True))
    op.add_column('member_group_coupons', sa.Column('user_redemption_period_type', sa.String(), nullable=True))
    op.add_column('member_group_coupons', sa.Column('group_redemption_period_limit', sa.Integer(), nullable=True))
    op.add_column('member_group_coupons', sa.Column('group_redemption_period_type', sa.String(), nullable=True))
    op.drop_constraint('member_group_coupons_coupon_id_fkey', 'member_group_coupons', type_='foreignkey')
    op.create_foreign_key(None, 'member_group_coupons', 'coupons', ['coupon_definition_id'], ['id'])
    op.drop_column('member_group_coupons', 'coupon_id')
    op.add_column('user_coupons', sa.Column('coupon_definition_id', sa.Integer(), nullable=True))
    op.add_column('user_coupons', sa.Column('name', sa.String(length=256), nullable=True))
    op.add_column('user_coupons', sa.Column('date_start', sa.Date(), nullable=True))
    op.add_column('user_coupons', sa.Column('date_end', sa.Date(), nullable=True))
    op.add_column('user_coupons', sa.Column('user_redemption_period_limit', sa.Integer(), nullable=True))
    op.add_column('user_coupons', sa.Column('user_redemption_period_type', sa.String(), nullable=True))
    op.add_column('user_coupons', sa.Column('all_machines', sa.Boolean(), nullable=True))
    op.add_column('user_coupons', sa.Column('applicable_machines', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_foreign_key(None, 'user_coupons', 'coupons', ['coupon_definition_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_coupons', type_='foreignkey')
    op.drop_column('user_coupons', 'applicable_machines')
    op.drop_column('user_coupons', 'all_machines')
    op.drop_column('user_coupons', 'user_redemption_period_type')
    op.drop_column('user_coupons', 'user_redemption_period_limit')
    op.drop_column('user_coupons', 'date_end')
    op.drop_column('user_coupons', 'date_start')
    op.drop_column('user_coupons', 'name')
    op.drop_column('user_coupons', 'coupon_definition_id')
    op.add_column('member_group_coupons', sa.Column('coupon_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'member_group_coupons', type_='foreignkey')
    op.create_foreign_key('member_group_coupons_coupon_id_fkey', 'member_group_coupons', 'coupons', ['coupon_id'], ['id'])
    op.drop_column('member_group_coupons', 'group_redemption_period_type')
    op.drop_column('member_group_coupons', 'group_redemption_period_limit')
    op.drop_column('member_group_coupons', 'user_redemption_period_type')
    op.drop_column('member_group_coupons', 'user_redemption_period_limit')
    op.drop_column('member_group_coupons', 'applicable_machines')
    op.drop_column('member_group_coupons', 'all_machines')
    op.drop_column('member_group_coupons', 'date_end')
    op.drop_column('member_group_coupons', 'date_start')
    op.drop_column('member_group_coupons', 'name')
    op.drop_column('member_group_coupons', 'coupon_definition_id')
    # ### end Alembic commands ###
