"""add_permissions_index

Revision ID: 20240806030108
Revises: 058a0d263066
Create Date: 2024-08-06 03:10:17.219679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20240806030108'
down_revision: Union[str, None] = '058a0d263066'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_permission_id', table_name='permissions')
    op.drop_index('ix_permission_name', table_name='permissions')
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.create_index('ix_permission_name', 'permissions', ['name'], unique=True)
    op.create_index('ix_permission_id', 'permissions', ['id'], unique=False)
    # ### end Alembic commands ###
