"""set_payment_method_token_nullable

Revision ID: 20241112075141
Revises: 20241109095853
Create Date: 2024-11-12 07:52:12.961551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20241112075141'
down_revision: Union[str, None] = '20241109095853'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('payment_methods_payment_token_key', 'payment_methods', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('payment_methods_payment_token_key', 'payment_methods', ['payment_token'])
    # ### end Alembic commands ###
