"""ucu_add_user_coupon_id

Revision ID: 20241021230853
Revises: 20241021115356
Create Date: 2024-10-21 23:10:55.355330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20241021230853'
down_revision: Union[str, None] = '20241021115356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_coupon_usages', sa.Column('user_coupon_id', sa.Integer(), nullable=True))
    op.add_column('user_coupon_usages', sa.Column('member_group_coupon_id', sa.Integer(), nullable=True))
    op.drop_constraint('user_coupon_usages_member_group_id_fkey', 'user_coupon_usages', type_='foreignkey')
    op.create_foreign_key(None, 'user_coupon_usages', 'member_group_coupons', ['member_group_coupon_id'], ['id'])
    op.create_foreign_key(None, 'user_coupon_usages', 'user_coupons', ['user_coupon_id'], ['id'])
    op.drop_column('user_coupon_usages', 'member_group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_coupon_usages', sa.Column('member_group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_coupon_usages', type_='foreignkey')
    op.drop_constraint(None, 'user_coupon_usages', type_='foreignkey')
    op.create_foreign_key('user_coupon_usages_member_group_id_fkey', 'user_coupon_usages', 'member_groups', ['member_group_id'], ['id'])
    op.drop_column('user_coupon_usages', 'member_group_coupon_id')
    op.drop_column('user_coupon_usages', 'user_coupon_id')
    # ### end Alembic commands ###
