"""fixcoupon

Revision ID: 20241109095853
Revises: 20241107232127
Create Date: 2024-11-09 09:59:13.643865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20241109095853'
down_revision: Union[str, None] = '20241107232127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('member_group_coupons_coupon_definition_id_fkey', 'member_group_coupons', type_='foreignkey')
    op.create_foreign_key(None, 'member_group_coupons', 'coupon_definitions', ['coupon_definition_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'member_group_coupons', type_='foreignkey')
    op.create_foreign_key('member_group_coupons_coupon_definition_id_fkey', 'member_group_coupons', 'coupons', ['coupon_definition_id'], ['id'])
    # ### end Alembic commands ###
