"""add_message

Revision ID: 20241107142103
Revises: 20241106160518
Create Date: 2024-11-07 14:21:18.387968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20241107142103'
down_revision: Union[str, None] = '20241106160518'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_messages', sa.Column('message', sa.String(length=400), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_messages', 'message')
    # ### end Alembic commands ###
