"""rp_add_user_id

Revision ID: 20241014123322
Revises: 20241008225840
Create Date: 2024-10-14 12:33:39.930151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20241014123322'
down_revision: Union[str, None] = '20241008225840'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reward_points', sa.Column('user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reward_points', 'user_id')
    # ### end Alembic commands ###
