"""mg_add_user_ids

Revision ID: 20241023013310
Revises: 20241023011325
Create Date: 2024-10-23 01:33:23.512829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20241023013310'
down_revision: Union[str, None] = '20241023011325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_groups', sa.Column('description', sa.String(length=1000), nullable=True))
    op.add_column('member_groups', sa.Column('user_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member_groups', 'user_ids')
    op.drop_column('member_groups', 'description')
    # ### end Alembic commands ###
