"""payment_add_user_id

Revision ID: 20241008225840
Revises: 20241003110650
Create Date: 2024-10-08 22:58:58.103542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20241008225840'
down_revision: Union[str, None] = '20241003110650'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.add_column('reward_points', sa.Column('balance', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reward_points', 'balance')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_column('payments', 'user_id')
    # ### end Alembic commands ###
