"""add is_active to user_qr_key

Revision ID: 20241003110650
Revises: 20241001010547
Create Date: 2024-10-03 11:07:22.518184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20241003110650'
down_revision: Union[str, None] = '20241001010547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_qr_keys', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_qr_keys', 'is_active')
    # ### end Alembic commands ###
