"""coupon_add_date

Revision ID: 20240920164525
Revises: 20240911120110
Create Date: 2024-09-20 17:15:35.753000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20240920164525'
down_revision: Union[str, None] = '20240911120110'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupons', sa.Column('customer_limit', sa.Integer(), nullable=True))
    op.add_column('coupons', sa.Column('voucher_limit', sa.Integer(), nullable=True))
    op.add_column('coupons', sa.Column('date_start', sa.Date(), nullable=True))
    op.add_column('coupons', sa.Column('date_end', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coupons', 'date_end')
    op.drop_column('coupons', 'date_start')
    op.drop_column('coupons', 'voucher_limit')
    op.drop_column('coupons', 'customer_limit')
    # ### end Alembic commands ###
