"""cd_fix_null

Revision ID: 20241023011325
Revises: 20241021230853
Create Date: 2024-10-23 01:13:54.848156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20241023011325'
down_revision: Union[str, None] = '20241021230853'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coupon_definitions', 'minimum_spending',
               existing_type=sa.NUMERIC(precision=15, scale=4),
               nullable=True)
    op.alter_column('coupon_definitions', 'criterial_cart_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coupon_definitions', 'criterial_cart_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('coupon_definitions', 'minimum_spending',
               existing_type=sa.NUMERIC(precision=15, scale=4),
               nullable=False)
    # ### end Alembic commands ###
