"""store_credit_txnadd_user_id

Revision ID: 20241103162609
Revises: 20241103121542
Create Date: 2024-11-03 16:26:26.148998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20241103162609'
down_revision: Union[str, None] = '20241103121542'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.add_column('store_credit_transaction', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_store_credit_transaction_order_id'), 'store_credit_transaction', ['order_id'], unique=False)
    op.create_index(op.f('ix_store_credit_transaction_user_id'), 'store_credit_transaction', ['user_id'], unique=False)
    op.add_column('transactions', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_transactions_order_id'), 'transactions', ['order_id'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_order_id'), table_name='transactions')
    op.drop_column('transactions', 'order_id')
    op.drop_index(op.f('ix_store_credit_transaction_user_id'), table_name='store_credit_transaction')
    op.drop_index(op.f('ix_store_credit_transaction_order_id'), table_name='store_credit_transaction')
    op.drop_column('store_credit_transaction', 'user_id')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_column('payments', 'order_id')
    # ### end Alembic commands ###
