"""mg_add_all_users

Revision ID: 20241107232127
Revises: 20241107142103
Create Date: 2024-11-07 23:25:19.074320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20241107232127'
down_revision: Union[str, None] = '20241107142103'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_groups', sa.Column('all_users', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member_groups', 'all_users')
    # ### end Alembic commands ###
