"""order_add_ref

Revision ID: 20241030072726
Revises: 20241023013310
Create Date: 2024-10-30 07:27:44.449018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20241030072726'
down_revision: Union[str, None] = '20241023013310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_ref', sa.String(length=20), nullable=True))
    op.add_column('orders', sa.Column('machine_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'machine_id')
    op.drop_column('orders', 'order_ref')
    # ### end Alembic commands ###
