"""update_user_model_slug

Revision ID: 20240911120110
Revises: 80f74f644934
Create Date: 2024-09-11 12:01:54.420662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20240911120110'
down_revision: Union[str, None] = '80f74f644934'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_slug', table_name='users')
    op.create_index(op.f('ix_users_slug'), 'users', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_slug'), table_name='users')
    op.create_index('ix_users_slug', 'users', ['slug'], unique=True)
    # ### end Alembic commands ###
