"""update_payment_methodr

Revision ID: 20240906113817
Revises: 20240902162037
Create Date: 2024-09-06 11:38:49.278914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20240906113817'
down_revision: Union[str, None] = '20240902162037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_methods', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('payment_methods', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_methods', 'updated_at')
    op.drop_column('payment_methods', 'created_at')
    # ### end Alembic commands ###
