"""add_user_message

Revision ID: 20241103121542
Revises: 20241030072726
Create Date: 2024-11-03 12:23:37.055923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20241103121542'
down_revision: Union[str, None] = '20241030072726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_messages_id'), 'user_messages', ['id'], unique=False)
    op.add_column('store_credit_transaction', sa.Column('order_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_credit_transaction', 'order_id')
    op.drop_index(op.f('ix_user_messages_id'), table_name='user_messages')
    op.drop_table('user_messages')
    # ### end Alembic commands ###
