"""payment_add_date

Revision ID: 20241015144453
Revises: 20241014123322
Create Date: 2024-10-15 14:45:11.377800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20241015144453'
down_revision: Union[str, None] = '20241014123322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('payments', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'updated_at')
    op.drop_column('payments', 'created_at')
    # ### end Alembic commands ###
