"""add_coupon_definition

Revision ID: 20240925152303
Revises: 20240923013632
Create Date: 2024-09-25 15:23:42.307114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20240925152303'
down_revision: Union[str, None] = '20240923013632'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupon_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('discount_type', sa.String(length=10), nullable=False),
    sa.Column('discount_amount', sa.DECIMAL(precision=15, scale=4), nullable=False),
    sa.Column('minimum_spending', sa.DECIMAL(precision=15, scale=4), nullable=False),
    sa.Column('minimum_spending_active', sa.Boolean(), nullable=True),
    sa.Column('criterial_cart_type', sa.String(length=10), nullable=False),
    sa.Column('criterial_cart_skus', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('criterial_cart_collections', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('target_type', sa.String(length=10), nullable=False),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('target_skus', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_collections', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('member_group_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_group_id'], ['member_groups.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupon_definitions_id'), 'coupon_definitions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coupon_definitions_id'), table_name='coupon_definitions')
    op.drop_table('coupon_definitions')
    # ### end Alembic commands ###
