"""store_credit_add_desc

Revision ID: 20241103212831
Revises: 20241103204411
Create Date: 2024-11-03 21:28:45.245156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20241103212831'
down_revision: Union[str, None] = '20241103204411'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_credit_transaction', sa.Column('description', sa.String(length=400), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_credit_transaction', 'description')
    # ### end Alembic commands ###
