"""source_id_nullable

Revision ID: 20241106160518
Revises: 20241106154258
Create Date: 2024-11-06 16:05:24.852475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20241106160518'
down_revision: Union[str, None] = '20241106154258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('skus', 'source_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('skus', 'source_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
