"""user_coupon_update

Revision ID: 20240927034220
Revises: 20240925152303
Create Date: 2024-09-27 03:50:19.956650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20240927034220'
down_revision: Union[str, None] = '20240925152303'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_coupons_member_group_id_fkey', 'user_coupons', type_='foreignkey')
    op.drop_constraint('user_coupons_coupon_id_fkey', 'user_coupons', type_='foreignkey')
    op.drop_column('user_coupons', 'coupon_id')
    op.drop_column('user_coupons', 'member_group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_coupons', sa.Column('member_group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_coupons', sa.Column('coupon_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_coupons_coupon_id_fkey', 'user_coupons', 'coupons', ['coupon_id'], ['id'])
    op.create_foreign_key('user_coupons_member_group_id_fkey', 'user_coupons', 'member_groups', ['member_group_id'], ['id'])
    # ### end Alembic commands ###
