"""payment_add_desc

Revision ID: 20241103204411
Revises: 20241103162609
Create Date: 2024-11-03 20:44:28.095592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20241103204411'
down_revision: Union[str, None] = '20241103162609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('transaction_id', sa.Integer(), nullable=True))
    op.add_column('payments', sa.Column('description', sa.String(length=400), nullable=True))
    op.create_index(op.f('ix_payments_transaction_id'), 'payments', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_transaction_id'), table_name='payments')
    op.drop_column('payments', 'description')
    op.drop_column('payments', 'transaction_id')
    # ### end Alembic commands ###
