"""Added Store Credit Transaction Table

Revision ID: 78de7b9db3be
Revises: ca0c43133fef
Create Date: 2024-06-26 08:55:24.022304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78de7b9db3be'
down_revision: Union[str, None] = 'ca0c43133fef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_credit_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('store_credit_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=15, scale=4), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['store_credit_id'], ['store_credits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_credit_transaction_id'), 'store_credit_transaction', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_store_credit_transaction_id'), table_name='store_credit_transaction')
    op.drop_table('store_credit_transaction')
    # ### end Alembic commands ###
